name: Release beta
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install npm dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Update the package version
        if: github.ref == 'refs/heads/dev'
        run: node scripts/update-package-version.js $GITHUB_RUN_ID

      - name: Publish beta release
        run: npm publish --tag next --access public
        if: github.ref == 'refs/heads/dev'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
