name: E2E Testing (Container)

on:
  workflow_dispatch:

jobs:
  testing:
    name: Start E2E Testing from container
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.1-jammy

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true
